name: Deploy frontend on release
on:
  push:
    branches: [ "release" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Create .env.production
        run: |
          cat > .env <<'EOF'
          VITE_API_BASE_URL="https://api.nextasoft.asia"
          EOF
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload dist
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: "/opt/ptop/frontend/releases/${{ github.sha }}/"
          strip_components: 1
      - name: Activate
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            REL="/opt/ptop/frontend/releases/${{ github.sha }}"
            test -d "$REL"
            ln -sfn "$REL" /opt/ptop/frontend/current
            if command -v nginx >/dev/null 2>&1; then
              sudo nginx -t && sudo nginx -s reload || true
            fi